services:
  redis:
    image: redis:7-alpine
    container_name: rate-limiter-redis
    ports:
      - "6379:6379"
    networks:
      - rate-limiter-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rate-limiter-app
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # Override hosts for Docker networking
      - REDIS_HOST=redis
    networks:
      - rate-limiter-network

networks:
  rate-limiter-network:
    driver: bridge

